# prefix: ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind -N "Show Tmux keybindings" ? display-popup -E -w 80% -h 70% -T "Tmux keybindings" "omarchy-menu-tmux-keybindings --print | less -R"

set-option -g focus-events on

# splits
bind \\ split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

bind -N "Create window" c new-window -c "#{pane_current_path}"

# switch windows (tabs) - shift + arrow
bind -n S-Left previous-window
bind -n S-Right next-window

# switch panes - alt + arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -sg escape-time 0
set -gw automatic-rename on

bind r source-file ~/.tmux.conf \; display "Reloaded"
